#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BRANCH_NAME=$(git symbolic-ref --short HEAD | tr -d '\n' | tr -d ' ')
echo "🪵 DEBUG: Branch is '$BRANCH_NAME'"

if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "develop" ]; then
  echo "🔓 Commit libre en rama $BRANCH_NAME"
  exit 0
fi

npx commitlint --edit "$1"
